-- MySQL Script generated by MySQL Workbench
-- сб, 06-кві-2019 21:42:54 +0300
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hotello
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `user_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_status` ;

CREATE TABLE IF NOT EXISTS `user_status` (
  `user_status_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL,
  PRIMARY KEY (`user_status_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users` ;

CREATE TABLE IF NOT EXISTS `users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_status_id` INT NOT NULL,
  `first_name` VARCHAR(128) NULL,
  `last_name` VARCHAR(128) NULL,
  `email` VARCHAR(128) NULL,
  `password_hash` VARBINARY(128) NULL,
  `salt` VARBINARY(128) NULL,
  `creation_time` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_users_user_status`
    FOREIGN KEY (`user_status_id`)
    REFERENCES `user_status` (`user_status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_users_user_status_idx` ON `users` (`user_status_id` ASC) VISIBLE;

CREATE UNIQUE INDEX `email_UNIQUE` ON `users` (`email` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `apartment_classes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apartment_classes` ;

CREATE TABLE IF NOT EXISTS `apartment_classes` (
  `id_apartment_class` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL,
  PRIMARY KEY (`id_apartment_class`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apartments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apartments` ;

CREATE TABLE IF NOT EXISTS `apartments` (
  `apartment_id` INT NOT NULL AUTO_INCREMENT,
  `id_apartment_class` INT NOT NULL,
  `places_amount` INT NULL,
  `rooms_amount` INT NULL,
  `description` MEDIUMTEXT NULL,
  `price_per_day` INT NULL,
  PRIMARY KEY (`apartment_id`),
  CONSTRAINT `fk_apartments_apartment_classes1`
    FOREIGN KEY (`id_apartment_class`)
    REFERENCES `apartment_classes` (`id_apartment_class`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_apartments_apartment_classes1_idx` ON `apartments` (`id_apartment_class` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bill` ;

CREATE TABLE IF NOT EXISTS `bill` (
  `bill_id` INT NOT NULL AUTO_INCREMENT,
  `amount_due` INT NULL,
  `bank_account_number` VARCHAR(80) NULL,
  PRIMARY KEY (`bill_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `orders` ;

CREATE TABLE IF NOT EXISTS `orders` (
  `id_order` INT NOT NULL AUTO_INCREMENT,
  `bill_bill_id` INT NOT NULL,
  `apartments_apartment_id` INT NOT NULL,
  `users_user_id` INT NOT NULL,
  `check_in` DATE NULL,
  `check_out` DATE NULL,
  `price_per_day` INT NULL,
  `total_price` INT NULL,
  `creation_time` DATETIME NULL,
  PRIMARY KEY (`id_order`),
  CONSTRAINT `fk_orders_apartments1`
    FOREIGN KEY (`apartments_apartment_id`)
    REFERENCES `apartments` (`apartment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_bill1`
    FOREIGN KEY (`bill_bill_id`)
    REFERENCES `bill` (`bill_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_orders_apartments1_idx` ON `orders` (`apartments_apartment_id` ASC) VISIBLE;

CREATE INDEX `fk_orders_users1_idx` ON `orders` (`users_user_id` ASC) VISIBLE;

CREATE INDEX `fk_orders_bill1_idx` ON `orders` (`bill_bill_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
